---
title: "Ideas for physical classifications of river networks"
subtitle: "Progress meeting 06.06.2024"
author: "Leo Helling"
title-slide-attributes:
  data-background-color: "#023e8a"
---

## first ideas

-   dominant land use
-   Urban pressure
-   Agricultural pressure
-   Confinement
-   Stream Power Index

## Dominant land use

land use category with highest share of valley bottom area.

-   urban areas + infrastructure

-   agricultural land

-   natural land (forest & grassland)

## Urban pressure

4 classes based on degree of urban landuse (could also be accumulated urban landuse from upstream areas!)

-   \>70 % highly urbanised

-   \>40 % urbanised

-   \>10 % moderately urbanised

-   \>0 % no urban land

## Agricultural impact

-   \>70 % strong agricultural impact

-   \>40 % high agricultural impact

-   \>10 % moderate agricultural impact

-   \>0 % no agricultural impact at all

## Confinement

proposed confinement index from 0-1 divided into 4 classes:

-   strongly confined
-   confined
-   weakly confined
-   unconfined

## Stream Power

idea: get discharge values from RHT network and calculate Streampower for each segment:

$$
\Omega=\rho g Q S
$$

''Ω'' is the stream power, ''ρ'' is the density of water (1000 kg/m\^3), ''g'' is Gravitational acceleration (9.8 m/s 2 ), ''Q'' is/ Discharge (m3/s), and ''S'' is the channel slope.

## Sinuosity

## Channel Pattern

## Bed Material

based on grainsize distribution
