#' #' render quarto files into output-folder
#' #'
#' #' @param report_file quarto document to be rendered
#' #'
#' #' @importFrom quarto quarto_render
#' #' 
#' #'
#' #' @examples
#' #' render_report("reports/2024-06-01-report.qmd")
#' render_report <- function(report_file) {
#'   output_file <- paste0("output/", sub(".qmd$", ".html", basename(report_file)))
#'   quarto::quarto_render(report_file, output_file = output_file)
#' }

require(fs)

# Find the latest HTML file generated by Quarto, together with its _file-folder
latest_html <- list.files("reports", pattern = "\\.html$", full.names = TRUE)
latest_html <- sort(latest_html, decreasing = TRUE)[1]
lates_folder <- paste0(sub("*.html", "", latest_html), "_files")

# delete existing files in docs to replace with latest
dirs <- fs::dir_ls("docs", type = "directory")
dirs_to_delete <- dirs[!dirs == file.path("docs", "reports")]
fs::dir_delete(dirs_to_delete)

# Copy the latest HTML file and its _files-filder into docs and rename it to index.html
file.copy(latest_html, "docs/index.html", overwrite = TRUE)
fs::dir_copy(path = lates_folder, 
             new_path = paste0("docs/", sub(".*/", "", lates_folder)), 
             overwrite = TRUE)