name: Render and Update Report

on:
  push:
    paths:
      - 'output/reports/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Find latest HTML output
      id: find_latest_output
      run: |
        latest_output=$(ls -t output/reports/*.html | head -n 1)
        echo "latest_output=$latest_output" >> $GITHUB_ENV

    - name: Update index.html
      run: |
        cp "${{ env.latest_output }}" index.html

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add index.html
        git commit -m "Update index.html to latest report"
        git push origin main
